### ISSUE TITLE
Xsrf Issue

### ISSUE THREAD

**Issue by aphenine** [marmelab/restful.js#108]
I'm trying to use this to rebuild an application I once got working with restangular, but using React.  

So far, I'm having lots of success and it's been a damn site easier than Angular, but the part that I'm having no joy is Xsrf, which Just Worked with restangular.  

I've been trying to generate the appropriate headers which might do something using a request interceptor.  However, I'm having absolutely no joy.  

I've tried using the solution at: https://github.com/marmelab/restful.js/issues/28 but updated to use the slightly different way it seems to want to call things since whatever version that was.  It does seem to have some kind of effect, in that an Allow-Control-Request-Headers field is added, along with an Allow-Control-Request-Method.  However, other than that, nothing.  Plus, the internet is not being helpful and the CORS stuff tells me my browser should be doing stuff with Origin or Referer (which it's just not bothering to do).  

I've cranked up my old Angular app and I notice there's lots of things missing in my current headers, as a result I'm failing CORS.  There's no token, no matter how I try, Origin does not get set, even if I pass it as part of the headers.  

I'm guessing that the preflight headers are different from my actual headers, but I have no idea how to set them properly and, well, it would be nice not to have to.  Given that this is meant to be a restangular replacement, it would be nice if this was easier to do, as that just required three lines of code, or if there was some up to date documentation on how to do this, failing that.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
