### ISSUE TITLE
patching an entity will not set 'PATCH' as method

### ISSUE THREAD

**Issue by fiws** [marmelab/restful.js#81]
but `patch` (lowercase)
I don't think that's how it should be.

![image](https://cloud.githubusercontent.com/assets/3409958/13199283/a2d029c8-d821-11e5-858b-1cf2215350cd.png)

**Comment by opengeek** [comment]
This is a big problem because of https://github.com/github/fetch/issues/37 ...

**Comment by opengeek** [comment]
Looks like this has to be fixed outside of fetch, as they are not going to normalize `patch` to uppercase.

**Comment by fiws** [comment]
restful.js should not rely on fetch normalizing the method names anyway IMO. Just supply the right method names..

**Comment by opengeek** [comment]
Agreed — I will try and submit a "patch" for this issue today that uppercases all the method names for consistency.

**Comment by fiws** [comment]
:+1: (that pun)

could just uppercase it here https://github.com/marmelab/restful.js/blob/master/src/model/endpoint.js#L16 
not sure if that will break anything though

**Comment by opengeek** [comment]
What do you think of the approach I've taken in #83 ? Instead of forcing all to uppercase, I thought it would be best to just define the methods of the endpoint as uppercase to begin with.

**Comment by fiws** [comment]
looks good :+1: 
waiting for merge.. :\

**Comment by RobinBressan** [comment]
Should be fixed by 0.9.6 thanks to @opengeek.

**Comment by fiws** [comment]
actually a breaking change – isn't it? Does restful.js not follow semver? :\

**Comment by RobinBressan** [comment]
Yes it does but I don't think this is a BC. The restful.js api was not updated.

**Comment by fiws** [comment]
What if projects relied on the "broken" patch method? Those will now eventually hit a roadblock.

**Comment by opengeek** [comment]
I don't believe it's possible to rely on the bug here, so this is not a BC break. AFAIK, patch wasn't working at all since the switch to using `fetch` and this simply fixes that bug and consistently addresses the source of the issue, which was the definition of the methods as lowercase and relying on the normalization of those methods to uppercase by fetch.

**Comment by fiws** [comment]
patch was "working" – it was just sending "patch" instead of "PATCH" to the server. The request reached my server.
It's ok for my if this is treated "non-breaking", just my thoughts.

**Comment by opengeek** [comment]
Well, it broke all of my projects using restful.js when the project moved to fetch because "patch" is not a valid method and the browser will not allow it due to CORS pre-flight checks. But perhaps this should increment the minor pre-1.0 version number to indicate the potential additional BC break on this method. I'll leave that to the maintainers to decide.
